services:

  app:
    build: .
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: hivex
      DB_USERNAME: root
      DB_PASSWORD: password

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_DATABASE: hivex
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
